const levelOneCard = [
    { title: 'Active Learning', description: 'Giving full attention to whatever people are saying, understanding, questioning, and interrupting only at appropriate times' },
    { title: 'Presentation', description: 'Public speaking, instruct, train or teach, perform' },
    { title: 'Time management', description: "Managing one's own time and the time of others" },
    { title: 'Persuading', description: 'Persuading others to change their minds or behaviour' },
    { title: 'Selling', description: 'Influence others to buy services, product or ideas and concepts' },
    { title: 'Monitoring', description: 'Monitoring performance of yourself, other individual to make inprovements or take corrective action' },
    { title: 'Troubleshooting', description: 'Determining causes of operating errors and actions to rectify' },
    { title: 'Science', description: 'Using scientific rules, methods and processes to solve problem' },
    { title: 'System analyis', description: 'Determining how a system work and changes in condition' },
    { title: 'Designing', description: 'Concieve, create, develop a plan, project' },
    { title: 'Operation Analysis', description: 'Analysing needs and product requirements to create a design' },
    { title: 'Programming', description: 'Writing computer programs for various purposes' },
    { title: 'Managing Material resources', description: 'Obtaining and seeing to the appropriate use of equipment, facilities needed to do certain work' },
    { title: 'Installation', description: 'Installing equipment, machines,wiring or programs to specification' },
    { title: 'Operation and Control', description: 'Controlling operations of equipement or systems' },
    { title: 'Repairing', description: 'Repairing machines or systems using tools' },
    { title: 'Quality Control Analysis', description: 'Conducting tests and inspections of products, services, to evaluate quality or performance' },
    { title: 'Equipment Maintenance', description: 'Performing routine maintenance on equipment and determining when and what kind of maintenance is needed' },
    { title: 'System Evaluation', description: 'Identifying measures of performance and the actions needed to improve or correct performace, relative to goals' },
    { title: 'Technology Design', description: 'Generating or adapting equipement and technology to user needs' },
    { title: 'Nurture', description: 'Culture and foster the developement of the individual in relation to health or skills and ability' },
    { title: 'Operations Monitoring', description: 'Watching gauges, dials, or other indicators to ensure machines work properly' },
    { title: 'Creating', description: 'Handicrafts, creating art, composing music' },
    { title: 'Instructing', description: 'Teaching others how to do something' },
    { title: 'Problem Solving', description: 'Deductive reasoning, idea generation, diagnose factors or issues' },
    { title: 'Managing Personnel resources', description: 'Motivating, developing and directing people as they work and identifying the best people for the job' },
    { title: 'Learning strategies', description: 'Selecting and using training/instructional methods when learning or teaching new things' },
    { title: 'Managing financial resources', description: 'Determining how money will be spent to complete work and accounting for expenditures' },
    { title: 'Administration', description: 'Working with systems, data and procedures attend to detail' },
    { title: 'Critical Thinking', description: 'Using logic and reasoning to identify the strengths and weakness of alternative solution approaches to problem' }
];

const levelTwoCard = [
    { title: 'Short commute', description: '' },
    { title: 'Casual hours', description: '' },
    { title: 'Quiet environment', description: '' },
    { title: 'Casual dress standards', description: '' },
    { title: 'Small employer(2-40 employer)', description: '' },
    { title: 'Work indoors', description: '' },
    { title: 'Evening/Shift Work', description: '' },
    { title: 'Defined, Routine Tasks', description: '' },
    { title: 'Teamwork', description: '' },
    { title: 'Job Share', description: '' },
    { title: 'Authority', description: '' },
    { title: 'Worthwhile products and services', description: '' },
    { title: 'Managing people', description: '' },
    { title: 'Task Variety', description: '' },
    { title: 'Large employer (500+ employees)', description: '' },
    { title: 'Managing Information Resources', description: '' },
    { title: 'Owner operator', description: '' },
    { title: 'Business Travel', description: '' },
    { title: 'Employment benefits', description: '' },
    { title: 'Client/Customer Contact', description: '' },
    { title: 'Family-friendly workplace', description: '' },
    { title: 'Sense of security', description: '' },
    { title: 'Full time', description: '' },
    { title: 'Promotions Gained through responsibilty', description: '' },
    { title: 'Medium employer(40-500 employees)', description: '' },
    { title: 'Flexible work hours', description: '' },
    { title: 'Work with people who share my ideas', description: '' },
    { title: 'Projet work', description: '' },
    { title: "Employer's values match my values", description: '' },
    { title: 'Air Conditioned Modern office', description: '' }
];

export { levelOneCard, levelTwoCard };
